name: tauso
channels:
  - conda-forge
dependencies:
  - shap
  - gdown
  - jupyterlab
  - matplotlib
  - seaborn
  - ipykernel
  - pip
  - pip:
    - -e .  # <--- CRITICAL: Installs your 'src' in editable mode

  # tooling
  - pytest
  - pytest-regressions
  - conda-build


