name: tauso

channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
 # core python deps (no build pins)
  - numpy
  - pandas
  - scipy
  - numba
  - biopython
  - bcbio-gff
  - gffutils
  - fuzzysearch
  - primer3-py
  - matplotlib
  - tqdm
  - simplejson
  - pytz
  - tomli
  - zipp
  - pympler
  - multiprocess
  - click
  - mysql-connector-python

  # your domain-specific stuff
  - codon-bias==0.3.5
  - viennarna==2.7.0
  - gget

  # tooling
  - pytest
  - pytest-regressions
  - conda-build