name: tauso

channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.11
 # core python deps (no build pins)
  - numpy
  - pandas
  - scipy
  - numba
  - biopython
  - bcbio-gff
  - gffutils
  - fuzzysearch
  - primer3-py
  - tqdm
  - simplejson
  - pytz
  - tomli
  - zipp
  - pympler
  - multiprocess
  - click
  - mysql-connector-python

  - bowtie

  - codon-bias==0.3.5
  - viennarna==2.7.0
  - gget
  - xgboost
