[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tauso"
version = "0.1.0"
description = "TAUSO: ASO design toolkit"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [{name = "Michael Kovaliov"}]

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.package-data]
"tauso._raccess" = [
    "install_raccess.sh",
    "patches/*.patch"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["tauso*"]

[project.scripts]

tauso = "tauso.cli:main"
